name: Docker

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**.jpg'
      - '**.png'

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    name: Build docker images
    runs-on: ubuntu-20.04
    env:
      TOKEN: ${{ secrets.DOCKERHUB }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - id: build
        run: |
          ./.ci/build_docker.sh
